import Sidebar from "@/components/custom/sidebar";
import "../globals.css";
import Navbar from "@/components/custom/navbar";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen w-full">
          <Sidebar />
          <div className="ml-[240px] w-full 2xl:ml-[280px]">
            <Navbar />
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
