import Sidebar from "@/components/custom/sidebar"
import '../globals.css'
import Navbar from "@/components/custom/navbar"
import { Separator } from "@/components/ui/separator"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full min-h-screen">
          <Sidebar/>
          <div className="w-full ml-[240px] 2xl:ml-[280px]">
            <Navbar/>
            <main className="p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
